choco/urls.py
from django.conf.urls import url

from . import views


app_name = 'choco'
urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^about/$', views.about_page, name='about'),
    url(r'^contacts/$', views.contacts_page, name='contacts'),
    url(r'^catalog/choco/$', views.catalog_choco, name='catalog_choco'),
    url(r'^catalog/beresta/(?P<subcategory_pk>[0-9]+)/$', views.catalog_beresta, name='catalog_beresta'),
    url(r'^catalog/wood/$', views.catalog_wood, name='catalog_wood'),
    url(r'^catalog/(?P<pk>[0-9]+)/$', views.details_page, name='details'),
    url(r'^cart/$', views.cart_page, name='cart'),

    url(r'^add/(?P<choco_pk>[0-9]+)/$', views.cart_add, name='cart_add'),
    url(r'^add_conf/(?P<choco_pk>[0-9]+)/(?P<config_pk>[0-9]+)/$', views.cart_add_conf, name='cart_add_conf'),
    url(r'^remove/(?P<choco_pk>[0-9]+)/(?P<config_pk>[0-9]+)/$', views.cart_remove, name='cart_remove'),
    url(r'^update/(?P<choco_pk>[0-9]+)/(?P<config_pk>[0-9]+)/$', views.cart_update, name='cart_update'),
    url(r'^cart_as_gift/$', views.cart_as_gift, name='cart_as_gift'),
    url(r'^cart_as_gift_package/(?P<package_pk>[0-9]+)/$', views.cart_as_gift_package, name='cart_as_gift_package'),

    url(r'^gift/$', views.gift_page, name='gift'),

    url(r'^gift/add/(?P<choco_pk>[0-9]+)/$', views.gift_add, name='gift_add'),
    url(r'^gift/remove/(?P<choco_pk>[0-9]+)/(?P<config_pk>[0-9]+)/$', views.gift_remove, name='gift_remove'),
    url(r'^gift/get_items/(?P<category_pk>[0-9]+)/(?P<subcategory_pk>[0-9]+)$', views.gift_get_items, name='gift_get_items'),
    url(r'^gift/state/$', views.gift_state, name='gift_state'),
    url(r'^gift/get_total_price/(?P<package_pk>[0-9]+)/$', views.gift_get_total_price, name='gift_get_total_price'),

    url(r'^gift/order/$', views.order_page),
    url(r'^gift/order/send/$', views.order_send),

    url(r'^order/$', views.order_page, name='order'),
    url(r'^order/send/$', views.order_send, name='order_send'),
    url(r'^send/$', views.message_send, name='message_send'),

    url(r'^quick_search$', views.quick_search, name='quick_search'),
    url(r'^search$', views.search_page, name='search'),
    
    url(r'^.well-known/acme-challenge/(?P<file>[a-zA-Z0-9_-]+)$', views.verify, name='verify')
]

superchoco/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('choco.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

choco/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Assortment, Configuration


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, label="", initial=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    configuration = forms.ModelChoiceField(required=False, queryset=Configuration.objects.all())
    old_configuration = forms.ModelChoiceField(required=False, initial=None, queryset=Configuration.objects.all())

    def __init__(self, item_id=-1, *args, **kwargs):
        super(CartAddProductForm, self).__init__(*args, **kwargs)
        if item_id != -1:
            self.fields['configuration'].queryset = Assortment.objects.get(pk=item_id).choco_config.all()


class GiftAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, label="", initial=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    configuration = forms.ModelChoiceField(required=False, queryset=Configuration.objects.all())
    old_configuration = forms.ModelChoiceField(required=False, initial=None, queryset=Configuration.objects.all())

    def __init__(self, item_id=-1, *args, **kwargs):
        super(GiftAddProductForm, self).__init__(*args, **kwargs)
        if item_id != -1:
            self.fields['configuration'].queryset = Assortment.objects.get(pk=item_id).choco_config.all()


class OrderForm(forms.Form):
    name = forms.CharField(label="Имя*")
    city = forms.CharField(label="Город", required=False)
    phone_number = forms.CharField(label="Контактный телефон*", widget=forms.TextInput(attrs={'placeholder': '+7(999)999-99-99'}))
    note = forms.CharField(label="Дополнительная информация", widget=forms.Textarea(), required=False)


class ContactForm(forms.Form):
    name = forms.CharField(label="Имя")
    phone = forms.CharField(label="Телефон", widget=forms.TextInput(attrs={'placeholder': '+7(999)999-99-99'}))

choco/views.py
# -*- coding: utf-8 -*-
import json
import os
from decimal import Decimal

from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.http import HttpResponse, FileResponse
from django.conf import settings
from django.db.models import Q

from .models import Assortment, Configuration, PackageStyle
from .cart import Cart, Gift
from .forms import CartAddProductForm, OrderForm, ContactForm
from .serializers import AssortmentSerializer, PackageStyleSerializer


sale_percent = Decimal(0.9)

def get_sale_percent(request, cart):
    total_price = cart.get_total_price()
    if len(cart) > 1:
        total_price = Decimal(total_price) * Decimal(sale_percent)
    if request.session.get('cart_package', False):
        total_price = round(Decimal(total_price) + Decimal(request.session['cart_package']['package_price']), 2)
    return total_price


EMAIL_FROM = 'russian.memento@gmail.com'
EMAIL_TO = 'chocosuvenir@yandex.ru'

#1-2-7 = old version
#1-2-8 = new version
URL_OLD = 'memento'

def home_page(request):
    contact_form = ContactForm()
    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True
    return render(request, 'home.html', {'contact_form': contact_form, 'redesign': redesign, 'url': request.build_absolute_uri()})


def about_page(request):
    contact_form = ContactForm()
    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True
    return render(request, 'about.html', {'contact_form': contact_form, 'redesign': redesign})


def contacts_page(request):
    contact_form = ContactForm()
    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True
    return render(request, 'contacts.html', {'contact_form': contact_form, 'redesign': redesign})


def details_page(request, pk):
    contact_form = ContactForm()

    choco_item = get_object_or_404(Assortment, pk=pk)
    choco_configs = choco_item.choco_config.all()
    first_choco_config = choco_item.choco_config.first()

    cart_form = CartAddProductForm(pk)

    if settings.DEBUG:
        static_dir = os.path.join(settings.BASE_DIR, u"choco/static/choco/choco_pics/")
    else:
        static_dir = os.path.join(settings.STATIC_ROOT, u"choco/choco_pics/")
    gallery_path = os.path.join(static_dir, choco_item.choco_dir)

    choco_gallery = []
    if os.path.isdir(gallery_path):
        for f in os.listdir(gallery_path):
            if f.lower().endswith("jpg") or f.lower().endswith("png"): # to avoid other files
                if not f.lower().endswith("_tn.jpg"):
                    choco_gallery.append("%s%s/%s" % (u"choco/choco_pics/", choco_item.choco_dir, f))

    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True

    return render(request, 'details.html', {
        'item': choco_item,
        'configurations': choco_configs,
        'cart_form': cart_form,
        'gallery': choco_gallery,
        'config_types_quantity': len(choco_item.choco_config.all()),
        'first_choco_config': first_choco_config,
        'contact_form': contact_form,
        'redesign': redesign
    })


def add_catalog_pagination(request, items_list):

    paginator = Paginator(items_list, 15)

    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return items

def catalog_choco(request):
    contact_form = ContactForm()

    items_list = Assortment.objects.filter(category_id=1, available=1).order_by('id')
    cart_form = CartAddProductForm(auto_id=False)
    items = add_catalog_pagination(request, items_list)

    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True

    return render(request, 'catalog.html', {'chocos': items, 'cart_form': cart_form, 'contact_form': contact_form, 'redesign': redesign})

def catalog_beresta(request, subcategory_pk):
    contact_form = ContactForm()

    items_list = Assortment.objects.filter(category_id=2, subcategory_id=subcategory_pk, available=1).order_by('id')
    cart_form = CartAddProductForm(auto_id=False)
    items = add_catalog_pagination(request, items_list)

    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True

    return render(request, 'catalog.html', {'chocos': items, 'cart_form': cart_form, 'contact_form': contact_form, 'redesign': redesign})

def catalog_wood(request):
    contact_form = ContactForm()

    items_list = Assortment.objects.filter(category_id=3, available=1).order_by('-id')
    cart_form = CartAddProductForm(auto_id=False)
    items = add_catalog_pagination(request, items_list)

    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True

    return render(request, 'catalog.html', {'chocos': items, 'cart_form': cart_form, 'contact_form': contact_form, 'redesign': redesign})


def cart_page(request):
    contact_form = ContactForm()

    cart = Cart(request)
    request.session['cart_as_gift'] = False
    total_price = cart.get_total_price()
    package_styles = PackageStyle.objects.all()

    if URL_OLD in request.build_absolute_uri():
        redesign = False
    else:
        redesign = True

    return render(request, 'cart.html', {'cart': cart, 'total_price': total_price, 'package_styles':package_styles, 'contact_form': contact_form, 'redesign': redesign})


def cart_as_gift_total_price(request, cart):
    total_price = cart.get_total_price()
    if request.session['cart_as_gift']:
        return get_sale_percent(request, cart)
    return total_price


def cart_add(request, choco_pk):
    cart = Cart(request)
    if request.method == 'POST':
        choco_item = get_object_or_404(Assortment, pk=choco_pk)
        if(int(request.POST.get("configId")) == -1):
            config_item = Configuration.objects.filter(assortment__id=choco_pk).first()
        else:
            config_item = get_object_or_404(Configuration, pk=request.POST.get("configId"))
        new_item = cart.add(
            item=choco_item,
            configuration=config_item,
            quantity=int(request.POST.get('newValue')),
            update_quantity=False
        )

        static_dir = u"/static/choco/choco_pics/"

        return HttpResponse(
            json.dumps({'result': "OK", 'cart': cart.cart, 'total_items': len(cart), "new_item": new_item, "static_dir": static_dir}),
            content_type="application/json"
        )

    return HttpResponse(
        json.dumps({'result': "OK", 'cart': cart.cart, 'total_items': len(cart)}),
        content_type="application/json"
    )

def cart_add_conf(request, choco_pk, config_pk=-1):
    cart = Cart(request)
    choco_item = get_object_or_404(Assortment, pk=choco_pk)
    form = CartAddProductForm(choco_pk, request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if config_pk != -1:
            config_item = get_object_or_404(Configuration, pk=config_pk)
            cart.add(item=choco_item, configuration=config_item, quantity=cd['quantity'], update_quantity=cd['update'])
        else:
            cart.add(item=choco_item, configuration=cd['configuration'], quantity=cd['quantity'], update_quantity=cd['update'])

    return redirect('choco:cart')

def cart_remove(request, choco_pk, config_pk):
    cart = Cart(request)
    total_cart_price = round(cart.get_total_price(), 2)
    if request.method == 'POST':
        product = get_object_or_404(Assortment, pk=choco_pk)
        configuration = get_object_or_404(Configuration, pk=config_pk)
        cart.remove(product, configuration)

        total_cart_price = round(cart.get_total_price(), 2)
        if request.session.get('cart_as_gift', False):
            total_cart_price = cart_as_gift_total_price(request, cart)

    return HttpResponse(
        json.dumps({'result': "OK", 'cart': cart.cart, 'total_items': len(cart), 'total_cart_price': total_cart_price}),
        content_type="application/json"
    )

def cart_update(request, choco_pk, config_pk):
    cart = Cart(request)
    total_price = 0
    total_cart_price = cart.get_total_price()
    if request.method == 'POST':
        product = get_object_or_404(Assortment, pk=choco_pk)
        configuration = get_object_or_404(Configuration, pk=config_pk)
        cart.add(
            item=product,
            configuration=configuration,
            quantity=int(request.POST.get('newValue')),
            update_quantity=True
        )
        for config in cart.cart[str(choco_pk)]:
            if config['configuration'] == config_pk:
                total_price = str(Decimal(config['price']) * config['quantity'])
                break

        total_cart_price = cart.get_total_price()
        if request.session.get('cart_as_gift', False):
            total_cart_price = cart_as_gift_total_price(request, cart)

    return HttpResponse(
        json.dumps({'result': "OK",
                    'cart': cart.cart,
                    'total_items': len(cart),
                    'total_price': total_price,
                    'total_cart_price': total_cart_price,
                    }),
        content_type="application/json"
    )

def cart_as_gift(request):
    cart = Cart(request)
    total_price = cart.get_total_price()
    if request.method == 'POST':
        request.session['cart_as_gift'] = False
        request.session['cart_package'] = False
    return HttpResponse(
        json.dumps({'result': "OK", 'cart': cart.cart, 'total_items': len(cart), 'total_price': total_price}),
        content_type="application/json"
    )

choco/templates/about.html
{% extends 'base.html' %}

{% block styles %}
{% endblock %}

<!-- эта строка для отображения изображений из папки static -->
{% load staticfiles %}

{% block content %}
    aboutpage
{% endblock %}

choco/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="keywords" content="подарок, сувенир, береста, шоколад">
        <meta name="description" content="Оригинальный русский сувенир">
        <!--meta name="viewport" content="width=device-width, initial-scale=1"-->
        {% if redesign %}
            <title>Русский Стиль</title>
        {% else %}
            <title>Русский Сувенир</title>
        {% endif %}

        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'choco/css/normalize.css' %}">

        {% if redesign %}
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/main.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/header.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/sidecart.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/catalog.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/cart.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/details.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/forms.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/home.css' %}"> 
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/gift.css' %}">
        {% else %}
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/main.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/header.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/sidecart.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/catalog.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/cart.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/details.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/forms.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/home.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'choco/css/old/gift.css' %}">
        {% endif %}

        <script src="{% static 'choco/jquery/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'choco/js/polyfill.js' %}"></script>
        <script src="{% static 'choco/js/cart.js' %}"></script>
        <script src="{% static 'choco/js/sidecart.js' %}"></script>
        <script src="{% static 'choco/js/gallery.js' %}"></script>
        <script src="{% static 'choco/js/contact.js' %}"></script>
        <script src="{% static 'choco/js/search.js' %}"></script>

		{% block styles %}
        {% endblock %}
    </head>

	{% load rupluralize_filter %}
    {% load staticfiles %}

    <body>
        {% csrf_token %}
        <div id="content">
            <div class="header">
                {% if redesign %}
                <div class="logo">Русский с<div class="t">т</div>иль</div>
                {% else %}
                <div class="logo">Русский сувенир</div>
                {% endif %}
                <div class="header-menu">
                    <div><a href="{% url 'choco:home' %}">Главная</a></div>
                    <div><a href="{% url 'choco:catalog_choco' %}">Из шоколада</a></div>
                    <div><a href="javascript:void(0)">Из бересты</a>
                        <div class="subcategory-selection">
                            <a href="{% url 'choco:catalog_beresta' 1 %}">Кружки</a>
                            <a href="{% url 'choco:catalog_beresta' 2 %}">Тарелки</a>
                            <a href="{% url 'choco:catalog_beresta' 3 %}">Туеса</a>
                            <a href="{% url 'choco:catalog_beresta' 10 %}">Батонницы</a>
                            <a href="{% url 'choco:catalog_beresta' 4 %}">Хлебницы</a>
                            <a href="{% url 'choco:catalog_beresta' 12 %}">Сухарницы</a>
                            <a href="{% url 'choco:catalog_beresta' 5 %}">Фляжки</a>
                            <a href="{% url 'choco:catalog_beresta' 6 %}">Шкатулки</a>
                            <a href="{% url 'choco:catalog_beresta' 11 %}">Бочонки</a>
                            <a href="{% url 'choco:catalog_beresta' 7 %}">Расчёски</a>
                            <a href="{% url 'choco:catalog_beresta' 8 %}">Заколки</a>
                            <a href="{% url 'choco:catalog_beresta' 9 %}">Прочее</a>
                            <a class="subcategory-small" href="{% url 'choco:catalog_beresta' 13 %}">Представительские</a>
                        </div>
                    </div>
                    <div><a href="{% url 'choco:catalog_wood' %}">Из дерева</a></div>
                    <div><a href="{% url 'choco:contacts' %}">Контакты</a></div>
                    <div><a id="open-cart" href="#">
                        {% if redesign %}
                            <img class="shopping-cart" src="{% static 'choco/images/shopping-cart.svg' %}">
                        {% else %}
                            <img class="shopping-cart" src="{% static 'choco/images/shopping-cart-old.svg' %}">
                        {% endif %}
                        <span class="cart-fill" id="total-items">
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                    {{ total_items }}
                                {% else %}
                                    0
                            {% endif %}
                        {% endwith %}
						</span>
                    </a></div>
                </div>
                <hr>
            </div>

            <div id="side-cart">
                <div class="cart-top">
                    <a id="close-cart" href="javascript:void(0)">✕</a>
                    <div class="cart-title">Корзина</div>
                    <div class="placeholder"></div>
                </div>
                <div class="cart-content-container">
                    <div class="cart-content" id="cart-content">
                        {% if cart|length < 1 %}
                            <div class="cart-empty">Корзина пуста!</div>
                        {% else %}
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <div class="cart-item" id="sidecart-item-{{item.product.id}}-{{item.configuration}}">
                                        <div class="wrapper">
                                            <div class="cart-item-image">
                                                {% if not product.choco_pic %}
                                                    <img src="{% static 'choco/choco_pics/default.png' %}"/>
                                                {% else %}
                                                    {% if redesign and 'tn' in product.choco_pic %}
                                                        {% with "choco/choco_pics/"|add:product.choco_dir|add:"/new_"|add:product.choco_pic as main_pic %}
                                                            <img src="{% static main_pic %}"/>
                                                        {% endwith %}
                                                    {% else %}
                                                        {% with "choco/choco_pics/"|add:product.choco_dir|add:"/"|add:product.choco_pic as main_pic %}
                                                            <img src="{% static main_pic %}"/>
                                                        {% endwith %}
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                            <div class="cart-item-info">
                                                <div>{{ product.choco_name }}</div>
                                                {% with configuration=item.conf_object %}
                                                    {% if configuration.weight %}
                                                        <div>Вес: {{ configuration.weight }} г</div>
                                                    {% endif %}
                                                {% endwith %}
                                                <div id="sidecart-quantity-{{item.product.id}}-{{item.configuration}}">Количество: <span class="sidecart-item-quantity">{{ item.quantity }}</span></div>
                                                <div>Цена: <span class="sidecart-item-total">{{ item.total_price }}</span> RUB</div>
                                            </div>
                                            <div class="delete-cross-wrap">
                                                <form class="cart-remove-item sidecart" action="" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" class="choco-pk" value="{{ product.id }}">
                                                    <input type="hidden" class="config-pk" value="{{ item.configuration }}">
                                                    <input type="submit" value="✕">
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                {% endwith %}
                            {% endfor %}
                        {% endif %}
                    </div>
                    {% if cart|length > 0 %}
                        <div class="sidecart-total">Общая стоимость: <span id="sidecart-total-num">{{ cart.get_total_price|floatformat:"-1" }}</span>р</div>
                    {% endif %}
                </div>
                <div class="sidecart-btn">
                    <a href="{% url 'choco:cart' %}">Перейти в корзину</a>
                </div>
            </div>
            {% block content %}
            {% endblock %}
        </div>

        <div id="order-call-modal">
            <div id="order-call-content">
                <div class="order-call-title">Заказать звонок</div>
                <form id="contact-form" method="post" action="">
                    {% csrf_token %}
                    <div class="order-call-input-wrap">
                        <span>Ваше имя</span>
                        <div class="order-call-input">{{ contact_form.name }}</div>
                    </div>
                    <div class="order-call-input-wrap">
                        <span>Ваш номер</span>
                        <div class="order-call-input">{{ contact_form.phone }}</div>
                    </div>
                    <input type="submit" value="Заказать" class="order-call-submit">
                </form>
            </div>
            <div id="order-call-triangle"></div>
        </div>

        <div class="modal" id="img-modal">
            <div class="modal-body">
                <div class="close-modal">✕</div>
                <img src="">         
            </div>
        </div>

        <div class="modal" id="catalog-modal">
            <div class="modal-body">
                <div id="catalog-modal-main">

                </div>
            </div>
            <div class="close-modal-outside">✕</div>
        </div>
    </body>
</html>

choco/templates/cart_table.html
<!-- эта строка для отображения изображений из папки static -->
{% load staticfiles %}
{% load static %}


{% for item in cart %}
    {% with product=item.product %}
        <tr id="product-{{ product.id }}-{{item.configuration}}">
            <td>
                <a href="{% url 'choco:details' product.id %}">
                    {% if not product.choco_pic %}
                        <img src="{% static 'choco/choco_pics/default.png' %}"/>
                    {% else %}
                        {% if redesign and 'tn' in product.choco_pic %}
                            {% with "choco/choco_pics/"|add:product.choco_dir|add:"/new_"|add:product.choco_pic as main_pic %}
                                <img src="{% static main_pic %}"/>
                            {% endwith %}
                        {% else %}
                            {% with "choco/choco_pics/"|add:product.choco_dir|add:"/"|add:product.choco_pic as main_pic %}
                                <img src="{% static main_pic %}"/>
                            {% endwith %}
                        {% endif %}
                    {% endif %}
                </a>
            </td>
            <td class="title">
                <a href="{% url 'choco:details' product.id %}"><span>{{ product.choco_name }}</span></a><br>
                {% with configuration=item.conf_object %}
                <span>
                    {% if configuration.size %}
                        Размер: {{ configuration.size }};
                    {% endif %}

                    {% if configuration.weight %}
                        Вес: {{ configuration.weight }};
                    {% endif %}

                    {% if configuration.diameter %}
                        Диаметр: {{ configuration.diameter }};
                    {% endif %}

                    {% if configuration.height %}
                        Высота: {{ configuration.height }};
                    {% endif %}

                    {% if configuration.width %}
                        Ширина: {{ configuration.width }};
                    {% endif %}

                    {% if configuration.length %}
                        Длина: {{ configuration.length }};
                    {% endif %}
                </span>
                {% endwith %}
            </td>
            <td class="amount">
                <form action="" method="post" class="cart-add-form">
                    {% csrf_token %}

                    <label product="{{ product.id }}" config="{{ item.configuration }}" class="quantity">
                        {#{ item.update_quantity_form.quantity }#}
                        <input type="number" name="quantity" value="{{ item.quantity }}" required="" id="id_quantity" min="1">
                        <a href="#" class="quantity-up"></a>
                        <a href="#" class="quantity-down"></a>
                    </label>

                    <input type="hidden" name="update" value="True" id="id_update">
                    {#{ item.update_quantity_form.update }#}
                    <!--input style="display: none" type="submit" value="Обновить"-->
                </form>
            </td>
            <td><span id="price-{{ product.id }}-{{item.configuration}}">{{ product.choco_price }}</span> RUB</td>
            <td><span id="total-price-{{ product.id }}-{{item.configuration}}">{{ item.total_price }}</span> RUB</td>
            <td class="delete">
                <div class="delete-cross-wrap">
                    <form class="cart-remove-item" action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" class="choco-pk" value="{{ product.id }}">
                        <input type="hidden" class="config-pk" value="{{ item.configuration }}">
                        <input type="submit" value="✕">
                        <!--a id="cart-remove-item-submit" href="" class="">✕</a-->
                    </form>
                </div>
            </td>
        </tr>
    {% endwith %}
{% endfor %}